# Generated by Django 4.2.5 on 2023-09-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pra_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='pra_app.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='pra_app.genre'),
        ),
    ]
