# Generated by Django 4.2.5 on 2023-09-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pra_app', '0003_rename_genre_game_genres_rename_genre_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
